### ISSUE TITLE
Latest cocoa pods doesn't support link_with

### ISSUE THREAD

**Issue by abelondev** [demetrio812/EurekaSwiftValidatorComponents#1]
Probably It should be 

target 'Examples' do
pod 'Eureka'
pod 'SwiftValidator', '3.0.3'
end

project 'Examples.xcodeproj'

**Comment by demetrio812** [comment]
Hello @abelondev, thanks for the comment, the latest release is the 0.39.0 as the 1.0 is still in beta. As soon as they release version 1.0 I will change the Podfile.

Thanks again,
Dem

**Comment by abelondev** [comment]
I just can’t build without changing. So this API is deprecated (recommended not to use for now)

**Comment by demetrio812** [comment]
What cocoapods version are you using? You are probably using the 1.0.beta5 that is a pre-release. With the latest release (0.39.0) that Podfile will not run. As I said, I'm waiting for the 1.0 to be released in order to change the Podfile, in the meantime you can change it manually if you want to test the Examples project (that Podfile is only needed for the Examples)

Thanks,
Dem

**Comment by skrosoft** [comment]
Cocoapods 1.0 is ready ;)

**Comment by demetrio812** [comment]
Just pushed the new Podfile
